### ISSUE TITLE
Dev a Login screen for the system

### ISSUE THREAD

**Issue by assafSabag** [startach/haprev#1]
![02](https://user-images.githubusercontent.com/12615452/27989329-e20786e0-643e-11e7-8e85-1ba3bc90b4e4.jpg)

**Comment by eladcandroid** [comment]
@assafSabag Please attach logo & background as PNG images

**Comment by assafSabag** [comment]
![image](https://user-images.githubusercontent.com/12615452/28686279-583a7fc4-7313-11e7-9c2a-31581bdca136.png)

**Comment by eladcandroid** [comment]
Done.
