### ISSUE TITLE
הוספת אפשרות להוסיף מידע לגבי מקום התנדבות

### ISSUE THREAD

**Issue by elad-sofer** [startach/haprev#49]
תינתן הרשאה לרכז לכתוב את הייחודיות בכל מקום

**Comment by idanlevi1** [comment]
להוסיף שדה ״פירוט אירוע״ בדף פתיחת אירוע (תחת ממשק רכזים)
_דרך הגעה:  ממשק רכזים (צריך הרשאה של רכז) -> פתיחת אירוע חדש_
ובנוסף לדאוג להציג את הפירוט בדף האירוע 
_הגעה: בחירת אירוע -> רשימת בתי חולים -> בחירת בית חולים -> בחירת אירוע_
