### ISSUE TITLE
login with facebook

### ISSUE THREAD

**Issue by assafSabag** [startach/haprev#5]
integrate with firebase

**Comment by eladcandroid** [comment]
@ygalbel What is the URL for your API example page?

**Comment by assafSabag** [comment]
https://startach.github.io/haprev-backend/

בתאריך 23 באוג׳ 2017 9:29 אחה״צ,‏ "Elad Cohen" <notifications@github.com>
כתב:

@ygalbel <https://github.com/ygalbel> What is the URL for your API example
page?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/startach/haprev/issues/5#issuecomment-324438563>, or mute
the thread

**Comment by eladcandroid** [comment]
Thanks. I also need an access to Facebook app settings to set it to work with React Native... Please send it to me in a private message (Slack or Whatsapp)
